[package]
name = "web_timing"
version = "1.0.0"
edition = "2021"
default-run = "web_timing"

[dependencies]
itertools = "0.10"
once_cell = "1.12.0"
actix-web = "4.0.1"
serde = { version = "1.0", features = ["derive"]}
reqwest = { version = "0.11", features = ["blocking"] }
rayon = "1.5"
