[package]
name = "cryptopals-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["web_timing"]

[profile.dev]
overflow-checks = false

[dependencies]
itertools = "0.10"
openssl = "0.10"
rand = "0.8"
num = "0.4"
num-bigint = { version = "0.4", features = ["rand"] }
once_cell = "1.12"
